### ISSUE TITLE
Consider enabling 1.6 feature flag on docs.rs

### ISSUE THREAD

**Issue by shepmaster** [codelabsab/rust-ocpp#23]
Or, if you don't want to, consider creating a placeholder module or avoiding linking to it. Right now, the [overview](https://docs.rs/rust-ocpp/latest/rust_ocpp/#v1_6) links to [a 404](https://docs.rs/rust-ocpp/latest/rust_ocpp/v1_6).

**Comment by tommymalmqvist** [comment]
Hi, I didn't think about this actully. I added

```toml
[package.metadata.docs.rs]
all-features = true
```

and bumped to 0.3.2.
